name: build for release
on:
  push:
    tags:
      - release*
  workflow_dispatch:

jobs:

  build-binary:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]
            - args: [--global, gulp, prettier, typescript]

      - run: |
          pnpm install 
          pnpm build 
          pnpm package
          

      - uses: actions/upload-artifact@v3
        with:
          name: build
          path: build/*.zip

  upload-release:
    permissions:
      contents: write
    needs:
      - build-binary
    runs-on: ubuntu-latest

    steps:

      - uses: actions/download-artifact@v3
        with:
          name: build
          path: build
          
      - run: ls -al build && ls -R build/ && file build/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: build/*